#
# Render GitHub Pages
#
# Build all resources that are deployed to GitHub Pages, and verify them. If
# triggered manually, deploy the result.
#

name: "Github Pages"

on:
  pull_request:
  push:
    branches-ignore: ["pr/**"]
    tags: ["**"]
  workflow_dispatch:

defaults:
  run:
    shell: "bash"

jobs:
  build:
    name: "Build Project Pages"

    runs-on: "ubuntu-latest"

    steps:
    - name: "Fetch Sources"
      uses: actions/checkout@v3
    - name: "Setup Pages"
      uses: actions/configure-pages@v3
    - name: "Prepare build"
      run: mkdir "./pages"

    - name: "Build Rust Documentation"
      run: make rust-doc

    - name: "Assemble Pages"
      run: cp -r "./target/doc" "./pages/doc"
    - name: "Upload pages"
      uses: actions/upload-pages-artifact@v1
      with:
        path: './pages'

  deploy:
    name: "Deploy Pages to Github"

    concurrency:
      cancel-in-progress: false
      group: "github-pages"

    environment:
      name: "github-pages"
      url: ${{ steps.deploy.outputs.page_url }}

    if: github.event_name == 'workflow_dispatch'
    needs: "build"

    permissions:
      id-token: "write"
      pages: "write"

    runs-on: "ubuntu-latest"

    steps:
    - name: "Deploy Pages"
      id: deploy
      uses: actions/deploy-pages@v2
